name: Run test-coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # pipeline actions
      - run: npm install
      - run: npm run test:cov

      # Reemplazamos el paso de codecov local por la acción oficial
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/pokedex-angular/lcov.info  # Asegúrate de que la ruta al archivo sea correcta
          flags: angular  # Puedes personalizarlo según el nombre de tu proyecto
          name: codecov-pokedex-angular  # Puedes darle un nombre único al reporte
          fail_ci_if_error: true  # Este paso es opcional: falla el CI si hay un error en la subida
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
